---
- hosts: all
  vars:
    root_dir: /ap-service
    sub_dir: ["logs", "conf", "app"]
    middleware: ["apache"]
  tasks:
    - name: Create Base Directory
      file:
        path: "{{ root_dir }}/{{ item[0] }}/{{ item[1] }}"
        state: directory
      with_nested:
        - "{{ sub_dir }}"
        - "{{ middleware }}"
      become: yes
    - name: Copy Apache Install file
      copy: 
        src: ../sh/apache_install.sh
        dest: /tmp/apache_install.sh
        mode: 0744
    - name: Apache Web Server Install
      command: sh /tmp/apache_install.sh
    - name: Copy Apache configuration file
      copy: 
        src: apache-conf/httpd.conf
        dest: /ap-service/conf/apache/httpd.conf
        owner: root
        group: root
        mode: 0644
      become: yes
    - name: AP Security Shell
      copy: 
        src: ../sh/ap_security.sh
        dest: /tmp/ap_security.sh
        mode: 0744
    - name: AP Security Setting
      command: sh /tmp/ap_security.sh
