---
- hosts: all
  vars:
    root_dir: /ap-service
    sub_dir: ["logs", "conf", "app"]
    middleware: []
  tasks:
    - name: Create Base Directory
      file:
        path: "{{ root_dir }}/{{ item[0] }}/{{ item[1] }}"
        state: directory
      with_nested:
        - "{{ sub_dir }}"
        - "{{ middleware }}"
      become: yes
    - name: Install common software requirements
      yum:
        state: latest
        name:
        - amazon-linux-extras
      become: yes
    - name: Copy Python3 & SQLite Install file
      copy: 
        src: ../sh/python3-sqlite3.sh
        dest: /tmp/python3-sqlite3.sh
        mode: 0744
    - name: Python3 & SQLite Install
      command: sh /tmp/python3-sqlite3.sh
    - name: AP Security Shell
      copy: 
        src: ../sh/ap_security.sh
        dest: /tmp/ap_security.sh
        mode: 0744
    - name: AP Security Setting
      command: sh /tmp/ap_security.sh
