- name: Amazon Linux based Apache2.4 AMI
  hosts: all
  vars:
    root_dir: /ap-service
    sub_dir: ["logs", "conf", "app"]
    middleware: ["apache"]
  pre_tasks:
    - name: Create Base Directory
      file:
        path: "{{ root_dir }}/{{ item[0] }}/{{ item[1] }}"
        state: directory
      with_nested:
        - "{{ sub_dir }}"
        - "{{ middleware }}"
      become: yes
  roles:
   - apache2.4
   - common