- name: Amazon Linux based Nginx1.18, Nodejs12 & PM2 AMI
  hosts: all
  vars:
    root_dir: /ap-service
    sub_dir: ["logs", "conf", "app"]
    middleware: ["nginx"]
  pre_tasks:
    - name: Create Base Directory
      file:
        path: "{{ root_dir }}/{{ item[0] }}/{{ item[1] }}"
        state: directory
      with_nested:
        - "{{ sub_dir }}"
        - "{{ middleware }}"
      become: yes
  roles:
   - nginx1.18
   - nodejs12
   - pm2
   - common