---
- hosts: all
  vars:
    root_dir: /ap-service
    sub_dir: ["logs", "conf", "app"]
    middleware: ["tomcat"]
  tasks:
    - name: Create Base Directory
      file:
        path: "{{ root_dir }}/{{ item[0] }}/{{ item[1] }}"
        state: directory
      with_nested:
        - "{{ sub_dir }}"
        - "{{ middleware }}"
      become: yes
    - name: Copy Tomcat Install file
      copy: 
        src: ../sh/tomcat_java_install.sh
        dest: /tmp/tomcat_java_install.sh
        mode: 0744
    - name: Tomcat Install
      command: sh /tmp/tomcat_java_install.sh
    - name: Copy Tomcat config file - catalina.sh
      copy: 
        src: tomcat-conf/catalina.sh
        dest: /ap-service/tomcat/bin/catalina.sh
    - name: Copy Tomcat config file
      copy: 
        src: tomcat-conf/server.xml
        dest: /ap-service/tomcat/conf/server.xml
      become: yes
    - name: AP Security Shell
      copy: 
        src: ../sh/ap_security.sh
        dest: /tmp/ap_security.sh
        mode: 0744
    - name: AP Security Setting
      command: sh /tmp/ap_security.sh